### ISSUE TITLE
This module is not ready for CJK characters

### ISSUE THREAD

**Issue by mashihua** [niieani/gpt-tokenizer#16]
We found that this module is not ready for CJK characters， when type `ここに内容を入力すると、消費されるメダルの数が計算されます。` 

OpenAI show:

<img width="716" alt="截屏2023-06-08 15 11 21" src="https://github.com/niieani/gpt-tokenizer/assets/230983/e55b1fcc-911e-4662-a513-232f573189c7">

This module show

<img width="1070" alt="截屏2023-06-08 15 12 04" src="https://github.com/niieani/gpt-tokenizer/assets/230983/079e6c78-c220-44b4-8277-8ae895c51d28">

The token is different to OpenAI.

**Comment by xnohat** [comment]
Above you use GPT-3 Encoder and below you use cl100k_base Encoder for GPT3.5 and GPT4
They are 2 difference token encoder , out 2 difference tokens set output

**Comment by foloinfo** [comment]
I checked the output with the same string with `p50k_base` and it seems to give the same result to OpenAI Tokenizer.
I also tested with a longer string (800 characters) and the number of tokens was the same.
I think it's working fine in CJK.

**Comment by niieani** [comment]
as folks in the replies explained, you have selected the incorrect encoder. The tokenizer works correctly.
