### ISSUE TITLE
Add support for `gpt-3.5-turbo-0613` and `gpt-3.5-turbo-16k-0613`

### ISSUE THREAD

**Issue by nilsreichardt** [niieani/gpt-tokenizer#19]
As listed in the [`README.md`](https://github.com/niieani/gpt-tokenizer#supported-models-and-their-encodings), there is no support for the new models:

* `gpt-3.5-turbo-0613`
* `gpt-3.5-turbo-16k-0613`

**Comment by niieani** [comment]
AFAIK all GPT-3.5 models use the same `cl100k_base` encodings.
