### ISSUE TITLE
Different calculating result between gpt-tokenizer and openai

### ISSUE THREAD

**Issue by Penggeor** [niieani/gpt-tokenizer#32]
<img width="1315" alt="image" src="https://github.com/niieani/gpt-tokenizer/assets/68799055/9fad3268-ba88-4286-9920-5dfd0908f4f8">
<img width="1586" alt="image" src="https://github.com/niieani/gpt-tokenizer/assets/68799055/3983a816-9ed0-46cb-99b8-d5dd34046886">

I am confuse why the calculating result is different from openai.

**Comment by kyeshmz** [comment]
Same as  #20
