### ISSUE TITLE
Import Issue on codebases with both module and common js files

### ISSUE THREAD

**Issue by gbrlmtrz** [niieani/gpt-tokenizer#4]
Hello! Let me start by saying this is a great fork, I love the isWithinTokenLimit utility!

We are having an issue in my organization when using this library, our codebase is split between commonjs and module javascript files, and for reasons outside of the scope here, we cannot define our project as modules on package.json.

**The issue is as follows:** When we import the library from an *.mjs file, node tries to import the files under /esm/*.js as common js files because of the extension, so it throws an error about invalid syntax.

![image](https://user-images.githubusercontent.com/12701019/234120288-431f06bb-1fff-4daf-bf6c-1a08f777c596.png)

This doesn't happen when importing from a *.cjs file
![image](https://user-images.githubusercontent.com/12701019/234122183-faab94e0-b2ec-45eb-90b2-3a43e050d288.png)

 We managed to fix by "proxying" the library through a .cjs file, which works but it is quite unelegant.

**Possible solution**: The generated files under /esm/ could have the *.mjs extension, so node can infer the proper type of file by the extension alone or something like this https://github.com/microsoft/TypeScript/issues/18442#issuecomment-1377529164

**How to reproduce**: https://github.com/gbrlmtrz/minimum-reproducable-tokenzier/tree/main  on node 18 and 16

**Comment by PaulKinlan** [comment]
For what it's worth - I'm experiencing a similar problem but the other way around. We use modules in a typescript environment and it can't find the exports :\

**Comment by niieani** [comment]
Thanks for reporting, should be fixed in the next version.

**Comment by timbuckley** [comment]
For any one else hitting this in TypeScript but using ESM, try importing like this:
```ts
import { encode } from 'gpt-tokenizer/cjs/main'
```
