### ISSUE TITLE
encodeChat: lineToEncode.match is not a function

### ISSUE THREAD

**Issue by BennyAlex** [niieani/gpt-tokenizer#47]
I get this error when using this als input chat:

```
     [
            {
                role: 'system',
                content:
                    'Please help with this error.'
            },
            {
                role: 'user',
                content: [
                    {
                        type: 'text',
                        text: 'The image on my website is not rendered'
                    }
                ]
            }
        ]
```

**Comment by niieani** [comment]
`content` expects a string, not an array. TypeScript's linting would have helped you discover this problem.

**Comment by BennyAlex** [comment]
Yeah but when using other features like images then it is an array.

**Comment by niieani** [comment]
It is correct for what this library supports.
If you're after tokenizing images, that is not yet supported: https://github.com/niieani/gpt-tokenizer/issues/41
PRs welcome.
