### ISSUE TITLE
Which encoding is this using?

### ISSUE THREAD

**Issue by ricardomatias** [niieani/gpt-tokenizer#5]
Thanks for your effort with this fork, it's so much faster. It's not clear to me which encoding is being used, is it `cl100k_base` or `r50k_base`? 

According to this [link](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb), `gpt-3-encoder` is using `r50k_base`, but I don't see any mention of it in the library.

**Comment by niieani** [comment]
This is using `r50k_base`, but I'm working making it customizable in v2.0.
