### ISSUE TITLE
BytePairEncodingCore.d.ts: 'TextDecoder' refers to a value, but is being used as a type here. Did you mean 'typeof TextDecoder'?

### ISSUE THREAD

**Issue by michael-engelhardt** [niieani/gpt-tokenizer#58]
I get an error in line 7 in the file `BytePairEncodingCore.d.ts`:
```
export declare const decoder: TextDecoder;
```

Should this be changed to?
```
export declare const decoder: typeof TextDecoder;
```

**Comment by niieani** [comment]
hi Michael, what's your stack? how are you using gpt-tokenizer? the d.ts files are autogenerated by TS during build time and are correct.
