### ISSUE TITLE
RangeError: Maximum call stack size exceeded on iOS Browsers (Safari & WebKit-based)

### ISSUE THREAD

**Issue by denizcdemirci** [niieani/gpt-tokenizer#62]
While using this package on an iOS device, I encounter a RangeError: Maximum call stack size exceeded error across all browsers, including Safari. Since all browsers on iOS devices using on WebKit, this issue affects all browsers on iOS. The error appears consistently, preventing the package from functioning correctly on iOS. I’ve confirmed that this issue is reproducible on the [package’s own demo page](https://gpt-tokenizer.dev/) as well, indicating a general compatibility issue with WebKit on iOS devices.

**Steps to Reproduce**

1. Open any iOS browser (tested on Safari and others, all WebKit-based) and navigate to the demo page for the package.
2. Observe the console log error: `RangeError: Maximum call stack size exceeded.`

![CleanShot 2024-10-31 at 22 18 37@2x](https://github.com/user-attachments/assets/215d3e24-5fab-467b-9b44-40a72a5ed995)

**Environment**

Package Version: 2.5.1
iOS Version: 18.1
iOS Browser: Safari (and other WebKit-based browsers)
Device: iPhone 14 Pro
**Note:** This issue appears exclusive to WebKit-based browsers on iOS. Since all iOS browsers are based on WebKit, users will encounter this issue across all browsers on iOS devices, not just Safari. Other platforms and browsers outside of iOS are unaffected.

**Comment by yigitkonur** [comment]
I have a similar issue. Considering that chat applications are very active on mobile, I think it's a priority. I'd really appreciate it if you could help.

**Comment by niieani** [comment]
Looking into this!

**Comment by niieani** [comment]
<img width="331" alt="Screenshot 2024-11-03 at 16 03 11" src="https://github.com/user-attachments/assets/e7f5b6a3-d5f6-4819-ad4f-7f6faa554693">

It looks like it's only happening with the o200k_base encoding (GPT-4o and o1). Might be due to the size of the tokenizer. Debugging further.

**Comment by pkukielka** [comment]
@niieani I can still reproduce this on Safari  17.2 (19617.1.17.11.9).
I checked both `2.9.0` and `2.6.0` release (to make sure it's not a regression from `2.6.0`) but problem is the same in both.
Also I tested various encodings and problem seems to be the same with all of them.

**Comment by niieani** [comment]
What's your device and browser where you can reproduce?

**Comment by pkukielka** [comment]
It is Mackbook M2 Pro.

```
uname -amnoprsv
Darwin vl-d-1525 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64 arm
```

I tried various encodings but effect was always the same. In particular I checked `cl100k_base`, `cl100k_base`, `o200k_base`.

If you have any idea how I can debug it further I will be super happy to assist with fixing it.

**Comment by pkukielka** [comment]
FYI looks like it crashes only if I try to include `gpt-tokenizer` like that:

`import { decode, encode } from 'gpt-tokenizer/encoding/cl100k_base'`

I changed it to be loaded using `require` and that fixed the issue:

`import('gpt-tokenizer/encoding/cl100k_base').then(tokenizer => /* ... */ )

**Comment by niieani** [comment]
What I find strange is that you can't reproduce on gpt-tokenizer.dev. What is the method of reproduction for you? Can you try [this CodeSandbox](https://codesandbox.io/p/sandbox/gpt-tokenizer-tjcjoz) or share your CodeSandbox repro?
