### ISSUE TITLE
[2.6.0] TS2835: Relative import paths need explicit file extensions

### ISSUE THREAD

**Issue by CryZo** [niieani/gpt-tokenizer#65]
Dear @niieani,
First of all I would like to thank you for this great library you have created. It helped me a lot over the last year. Unfortunately, the last minor update broke it for me. With version 2.6.0 I get this TypeScript error:
```
node_modules/gpt-tokenizer/esm/models.d.ts(1,35): error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './mapping.js'?
```
I wonder if this error is expected? Do I need to change my import? Or is this a bug?
As a workaround, I stuck with 2.5.0, which still works as intended.

**Comment by niieani** [comment]
next version (2.6.1) should fix this.

**Comment by CryZo** [comment]
That worked absolutely fine. Thanks for your fast fix! :heart_hands:
